version: '3.5'

services:
  php:
    build: ./dev/docker/php
    container_name: "php"
    volumes:
      - ./:/var/www/app:delegated
    depends_on:
      - mysql

  web:
    image: nginx:1.19.1-alpine
    container_name: "web"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app:delegated
      - ./dev/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php

  mysql:
    image: mysql:8.0.21
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3333:3306"

  mongo:
    image: mongo:4.2.8
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet

volumes:
  mysql-data:
    name: data_mysql
  mongo-data:
    name: data_mongo
